<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Marko-PC" name="tests.meterreadings.AddMeterReadingsForExistingProfileTest" tests="1" failures="0" timestamp="4 Mar 2018 22:58:00 GMT" time="0.093" errors="1">
  <testcase name="addMeterReadingsForSpecificProfile_meterReadingsAdded" time="0.093" classname="tests.meterreadings.AddMeterReadingsForExistingProfileTest">
    <error type="java.lang.AssertionError" message="[Incorrect validation message] 
Expecting:
 &lt;&quot;Validation error :  Expected consumption for profile A and month JAN is between 289.575-482.62499999999994 but current consumption is 54
&quot;&gt;
to contain:
 &lt;&quot;Success&quot;&gt; ">
      <![CDATA[java.lang.AssertionError: [Incorrect validation message] 
Expecting:
 <"Validation error :  Expected consumption for profile A and month JAN is between 289.575-482.62499999999994 but current consumption is 54
">
to contain:
 <"Success"> 
	at tests.meterreadings.AddMeterReadingsForExistingProfileTest.addMeterReadingsForSpecificProfile_meterReadingsAdded(AddMeterReadingsForExistingProfileTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addMeterReadingsForSpecificProfile_meterReadingsAdded -->
</testsuite> <!-- tests.meterreadings.AddMeterReadingsForExistingProfileTest -->
